- name: Install Ganglia
  apt:
    name: ganglia-monitor
    state: present

- name: Configure Ganglia
  template:
    src: ganglia/gmond.conf.j2
    dest: /etc/ganglia/gmond.conf
    owner: root
    group: root
    mode: 0644
