# we have to make sure that the disk is NOT mounted by cloud-init beforehand
- name: mount disk
  mount:
    path: /vol/scratch
    src: "{{ ephemerals[0] }}"
    fstype: ext4
    state: mounted
  when:
    - ephemerals