# Install gridengine-client on all slaves

- name: Install gridengine packages
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - gridengine-client # Utilities for Grid Engine queue management
    - gridengine-exec # Distributed resource management - Execution Server

- name: Update act_qmaster
  copy:
    content: "{{ master.hostname }}"
    dest: /var/lib/gridengine/default/common/act_qmaster
    owner: sgeadmin
    group: sgeadmin
    mode: 0644
  register: act_qmaster

# Make sure that master daemon is running
- name: Start gridengine exec daemon
  systemd:
    name: gridengine-exec
    state: started






