- hosts: master
  become: yes
  vars_files:
      - "vars/common.yml"
  roles:
    - common
    - master

- hosts: slaves
  become: yes
  vars_files:
      - "vars/common.yml"
  roles:
  - common
  - slave