- hosts: master
  become: yes
  vars_files:
      - "vars/common.yml"
  roles:
    - role: common,master

- hosts: slaves
  become: yes
  vars_files:
      - "vars/common.yml"
  roles:
  - role: common,slave