- name: Disable swap
  shell: swapoff -a

- name: Allow bridge nf traffic
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.bridge.bridge-nf-call-iptables = 1'
    state: present

- shell: "sysctl -p"

- name: Reset kubeadm
  shell: "kubeadm reset -f"
  args:
    creates: /etc/kubernetes/discovery-token-ca-cert-hash

- name: Initialize kubeadm
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16"
  args:
    creates: /etc/kubernetes/discovery-token-ca-cert-hash

- name: Get & store discovery-token-ca-cert-hash
  shell: "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null |    openssl dgst -sha256 -hex | sed 's/^.* //' > /etc/kubernetes/discovery-token-ca-cert-hash"
  args:
    creates: /etc/kubernetes/discovery-token-ca-cert-hash

- name: Enable and start kublet service
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Create K8s configuration for default user (1/3)
  file:
    path: "/home/{{ansible_env.SUDO_USER}}/.kube"
    state: directory
    owner: "{{ansible_env.SUDO_USER}}"
    group: "{{ansible_env.SUDO_USER}}"
    mode: 0755

- name: Create K8s configuration for default user (2/3)
  copy:
    remote_src: true
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/{{ansible_env.SUDO_USER}}/.kube/config"

- name: Create K8s configuration for default user (3/3)
  file:
    path: "/home/{{ansible_env.SUDO_USER}}/.kube/config"
    owner: "{{ansible_env.SUDO_USER}}"
    group: "{{ansible_env.SUDO_USER}}"
    mode: 0750

- name: Create K8s configuration for root user (1/3)
  file:
    path: "/root/.kube"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create K8s configuration for root user (2/3)
  copy:
    remote_src: true
    src: "/etc/kubernetes/admin.conf"
    dest: "/root/.kube/config"

- name: Create K8s configuration for root user (3/3)
  file:
    path: "/root/.kube/config"
    owner: root
    group: root
    mode: 0750


- name: Get pod network deployment yaml
  get_url:
    url: https://cloud.weave.works/k8s/v1.10/net.yaml
    dest: /etc/kubernetes/net.yml

- name: Create pod network
  k8s:
    state: present
    src: /etc/kubernetes/net.yml

