- include: 001-monitor.yml
- include: 005-disk.yml

- include: 010-nfs.yml
  when:
    - enable_nfs == 'yes'
- include: 020-gridengine.yml
  when:
    - enable_gridengine == 'yes'
- include: 030-mesos.yml
  when:
    - enable_mesos == 'yes'

- include: 999-cloud9.yml
  when:
    - enable_cloud9 == 'yes'